<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:15:01.
 */
class htmlResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var htmlResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new htmlResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers htmlResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::load
     * @todo   Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::start
     * @todo   Implement testStart().
     */
    public function testStart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::getImageIfExists
     * @todo   Implement testGetImageIfExists().
     */
    public function testGetImageIfExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadImage
     * @todo   Implement testLoadImage().
     */
    public function testLoadImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::getUrlImage
     * @todo   Implement testGetUrlImage().
     */
    public function testGetUrlImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadExternImage
     * @todo   Implement testLoadExternImage().
     */
    public function testLoadExternImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::addSytle
     * @todo   Implement testAddSytle().
     */
    public function testAddSytle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::loadCssIfExists
     * @todo   Implement testLoadCssIfExists().
     */
    public function testLoadCssIfExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::loadCss
     * @todo   Implement testLoadCss().
     */
    public function testLoadCss() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::loadExternCss
     * @todo   Implement testLoadExternCss().
     */
    public function testLoadExternCss() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::getCssFile
     * @todo   Implement testGetCssFile().
     */
    public function testGetCssFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::getLink
     * @todo   Implement testGetLink().
     */
    public function testGetLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::getActionLinkIfHasPermission
     * @todo   Implement testGetActionLinkIfHasPermission().
     */
    public function testGetActionLinkIfHasPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::MakeLink
     * @todo   Implement testMakeLink().
     */
    public function testMakeLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadJQueryFunction
     * @todo   Implement testLoadJQueryFunction().
     */
    public function testLoadJQueryFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadJsFunction
     * @todo   Implement testLoadJsFunction().
     */
    public function testLoadJsFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadJs
     * @todo   Implement testLoadJs().
     */
    public function testLoadJs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadPlugin
     * @todo   Implement testLoadPlugin().
     */
    public function testLoadPlugin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadAngular
     * @todo   Implement testLoadAngular().
     */
    public function testLoadAngular() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::LoadJQuery
     * @todo   Implement testLoadJQuery().
     */
    public function testLoadJQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::isStarted
     * @todo   Implement testIsStarted().
     */
    public function testIsStarted() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::getStartedArray
     * @todo   Implement testGetStartedArray().
     */
    public function testGetStartedArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers htmlResource::flush
     * @todo   Implement testFlush().
     */
    public function testFlush() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
