<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:15:01.
 */
class paginatorResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var paginatorResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new paginatorResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers paginatorResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::setWhere
     * @todo   Implement testSetWhere().
     */
    public function testSetWhere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::setJoin
     * @todo   Implement testSetJoin().
     */
    public function testSetJoin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::setDados
     * @todo   Implement testSetDados().
     */
    public function testSetDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::Paginacao
     * @todo   Implement testPaginacao().
     */
    public function testPaginacao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::startDebug
     * @todo   Implement testStartDebug().
     */
    public function testStartDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::stopDebug
     * @todo   Implement testStopDebug().
     */
    public function testStopDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::debuggin
     * @todo   Implement testDebuggin().
     */
    public function testDebuggin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::setPaginationType
     * @todo   Implement testSetPaginationType().
     */
    public function testSetPaginationType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::selecionar
     * @todo   Implement testSelecionar().
     */
    public function testSelecionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::draw
     * @todo   Implement testDraw().
     */
    public function testDraw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::getLimit
     * @todo   Implement testGetLimit().
     */
    public function testGetLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::getOffset
     * @todo   Implement testGetOffset().
     */
    public function testGetOffset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers paginatorResource::getLastCount
     * @todo   Implement testGetLastCount().
     */
    public function testGetLastCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
