<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:12:22.
 */
class drawPaginatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var drawPaginator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new drawPaginator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers drawPaginator::setHtmlObj
     * @todo   Implement testSetHtmlObj().
     */
    public function testSetHtmlObj() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers drawPaginator::imprime
     * @todo   Implement testImprime().
     */
    public function testImprime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers drawPaginator::setSaved
     * @todo   Implement testSetSaved().
     */
    public function testSetSaved() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers drawPaginator::setModel
     * @todo   Implement testSetModel().
     */
    public function testSetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers drawPaginator::drawPages
     * @todo   Implement testDrawPages().
     */
    public function testDrawPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
